# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'EmergencyPreparednessApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EmergencyPreparednessApp
  pod 'BMSCore', '~> 2.0'
  pod 'BMSPush', '~> 3.0'
  pod 'PKHUD', '~> 5.0'
  pod 'AppAuth'
  pod 'AppCenter'
  
end
